### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by caweinshenker** [cshort101/gmsl_driver#2]
From the README it is not clear to me whether this can be compiled on the DrivePX2. I'd assume so, but I run into these issues when trying to make on the DrivePX2.

~~~
Errors     << gmsl_single_camera:make /home/nvidia/catkin_ws/logs/gmsl_single_camera/build.make.001.log
In file included from /home/nvidia/catkin_ws/src/gmsl_driver/src/WindowEGL.cpp:36:0:
/usr/include/xf86drmMode.h: In function ‘int drm_property_type_is(drmModePropertyPtr, uint32_t)’:
/usr/include/xf86drmMode.h:250:24: error: ‘DRM_MODE_PROP_EXTENDED_TYPE’ was not declared in this scope
  if (property->flags & DRM_MODE_PROP_EXTENDED_TYPE)
                        ^
make[2]: *** [CMakeFiles/gmsl_single_camera_node.dir/src/WindowEGL.cpp.o] Error 1
make[1]: *** [CMakeFiles/gmsl_single_camera_node.dir/all] Error 2
make: *** [all] Error 2
~~~

Can you provide more detail on the compilation process?

[cmake_out.txt](https://github.com/cshort101/gmsl_driver/files/1219127/cmake_out.txt)

**Comment by hans-ob1** [comment]
have the same problem

**Comment by caweinshenker** [comment]
I googled the missing constant and added it into xf86drmMode.h. I have no idea whether it will cause some obscure bug way down the line, but so far so good.

**Comment by MadBiceps** [comment]
@caweinshenker we have the same problem. Can you give us your constant there you added to the xf86drmMode.h that it works?

**Comment by harderthan** [comment]
I have the same problem. 
Could you give us your constant there you added to the xf86drmMode.h.
Please.

**Comment by harderthan** [comment]
Hi, All.

I did find the constant on this [link](https://lists.freedesktop.org/archives/dri-devel/2014-June/061078.html
)
And I added this line. 

```cpp
...
 #define DRM_MODE_PROP_EXTENDED_TYPE	0x0000ffc0
...

**Comment by caweinshenker** [comment]
Hi all,

I only had access to a DrivePX2 through a temporary research stay. I've since left that position and won't be able to do any maintenance or offer much support. I believe @harderthan has the correct answer for this one.

**Comment by atasoglou** [comment]
Is this `#define DRM_MODE_PROP_EXTENDED_TYPE	0x0000ffc0` the solution for now?
